---
title: "Analisi Dati e Statistica"
subtitle: "Università di Trento, Dipartimento di Ingegneria Industriale"
author: "Paolo Bosetti"
---

# Contenuti del corso

0.  [Introduzione al corso](0-intro){target="_blank"}
1.  [Statistica descrittiva e inferenziale](1-statistica){target="_blank"}
2.  [Introduzione a R](2-R-intro){target="_blank"}
3.  [Regressione](3-regressione){target="_blank"}
4.  [Bootstrap](4-bootstrap){target="_blank"}
5.  [Misura, incertezza, taratura](5-misura){target="\"_blank"}
6.  [*Design of Experiments*](6-DoE){target="\"_blank"}
7.  [Serie temporali](7-serie_temporali){target="_blank"}


:::callout-important
## Aggornamenti continui!

Le slide qui presentate possono essere frequentemente aggiornate per correzioni e piccole aggiunte: assicuratevi di verificare sempre l'ultima versione (basta ricaricare la pagina!)
:::


# Uso

Le slide sono interattive. I comandi più utili sono:

-   `F` per presentare a tutto schermo
-   `E` per la modalità esportazione (poi stampare come PDF dal browser); `E` di nuovo per uscire dalla modalità esportazione
-   Tasti cursore per navigare avanti e indietro
-   `ESC` per passare alla modalità overview
-   `?` per altri comandi


