project:
  type: website

website:
  title: "Paolo Bosetti"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - various.qmd
      - about.qmd
  repo-url: https://github.com/pbosetti/teaching_site
  repo-actions: [source, issue]

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
comments:
  hypothesis: true



