project:
  type: website
  render:
    - "*.qmd"
    - "!_*.qmd"

website:
  title: "Paolo Bosetti"
  reader-mode: true
  google-analytics: "G-77EMP7T5YY"
  cookie-consent:
    type: express
    style: simple
    palette: light
  navbar:
    left:
      - text: ADAS
        menu:
          - href: slides/ADAS/index.qmd
            text: Contenuti
          - href: slides/ADAS/0-intro.qmd
            text: Intro
          - href: slides/ADAS/1-statistica.qmd
            text: Statistica
          - href: slides/ADAS/2-R-intro.qmd
            text: Linguaggio R
          - href: slides/ADAS/3-regressione.qmd
            text: Regressione
          - href: slides/ADAS/4-bootstrap.qmd
            text: Bootstrap
          - href: slides/ADAS/5-misura.qmd
            text: Misura
          - href: slides/ADAS/6-DoE.qmd
            text: Design of Experiments
          - href: slides/ADAS/7-serie_temporali.qmd
            text: Serie temporali
      - text: DESAnED
        menu:
          - href: desaned.qmd
            text: Table of Contents
          - href: /desaned/1-statistics.html
            text: Statistics
          - href: /desaned/2-R-intro.html
            text: Intro to R language
          - href: /desaned/3-regression.html
            text: Regression
          - href: /desaned/4-kfold.html
            text: K-Fold validation
          - href: /desaned/5-DoE.html
      #       text: Design of Experiments
      # - various.qmd
      - data.qmd
      - text: "Blog"
        href: /blog/index.html
      - about.qmd
    right:
      - href: https://github.com/pbosetti/teaching_site
        text: "This project on GitHub"
        icon: github
  page-footer:
    background: light
    border: true
    left: |
      [![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.eu.png){height='30'}](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: 
      - icon: github
        href: https://github.com/pbosetti
  repo-url: https://github.com/pbosetti/teaching_site
  repo-actions: [source, issue]
  
html-math-method: mathjax

format:
  html:
    theme: 
      - cerulean
      - styles.scss
    toc: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    
comments:
  hypothesis: false



